### ISSUE TITLE
Installing Flake8 on the Vagrant env 

### ISSUE THREAD

**Issue by RonTuretzky** [redhat-beyond/commune#10]
hey @ofirtzabari 

can you run the following command

pipenv install --dev flake8

and then add the Pipfile and the Pipfile.lock files into the repo as well? 

Thanks!

**Comment by ofirtzabari** [comment]
Ok, I will do it today

**Comment by RonTuretzky** [comment]
@kobihk adding the line you suggested 
`flake8  "*"`

under dev packages did not resolve the issue, any other suggestions?

**Comment by RonTuretzky** [comment]
ofir fixed it by changing the piplock file, closing issue
