### ISSUE TITLE
User functions

### ISSUE THREAD

**Issue by ofirtzabari** [redhat-beyond/commune#47]
implement user functions after all the models are marged
add vote function

**Comment by RonTuretzky** [comment]
![image](https://user-images.githubusercontent.com/74178515/211816622-135b38a9-2247-4302-a352-e66d746b89a1.png)


Implement these functions

**Comment by RonTuretzky** [comment]
And also something like this 

![image](https://user-images.githubusercontent.com/74178515/211816773-dfd4b0f4-b64a-4690-80e6-31ce32e0aede.png)


but with the fields for our user object 

https://github.com/dotja/django_pytest_tutorial/blob/master/myuser/models.py you can use this for inspiration

**Comment by ofirtzabari** [comment]
![image](https://user-images.githubusercontent.com/100446995/211817535-60852503-474d-4273-808f-81854b21e952.png)
help?

**Comment by RonTuretzky** [comment]
@ofirtzabari  

for the vote you have to use the vote model to create a new instance, I think you need chore_id as an additional function parameter, you don't need a vote_id because it shouldn't exist until you use this function 

For  execute chore, you need to have a chore_id and just change the field of that chore 

call me if something is unclear

**Comment by ofirtzabari** [comment]
Wait one object is one vote?
I think one object is for all votes for some chore

**Comment by RonTuretzky** [comment]
![image](https://user-images.githubusercontent.com/74178515/211819054-e2240d52-780a-4fdc-ab80-f2d95ea9d769.png)


> Wait one object is one vote? I think one object is for all votes for some chore

So every vote instance has what chore it's on, and true/false 

So every object of the vote model is one vote. 

So if you want all the votes for a chore you have to do 

Votes.objects.filter(choreid=_choreid) 

and then you get all the votes on that chore

@ofirtzabari does that make sense?
