### ISSUE TITLE
Commune Page 

### ISSUE THREAD

**Issue by RonTuretzky** [redhat-beyond/commune#67]
Page which presents commune data

**Comment by RonTuretzky** [comment]
- [ ] User data 
- [ ] Wallet 
- [ ] Active chores 
- [ ] Chores to vote on 
- [ ] Description 
-

**Comment by EliasAndry** [comment]
we need to add a method that let client create their own commune or we can add them manually and clients choose between them and each commune got their own chores

**Comment by RonTuretzky** [comment]
Creating issue

**Comment by RonTuretzky** [comment]
- [ ] User data
- [ ]  Wallet
- [ ]  Active chores
- [ ]  Chores to vote on
- [ ]  Description
- [ ] a filter to choose between diff communes on the commune page


@EliasAndry @FaezZangariya @ofirtzabari Updated TODO list
