### ISSUE TITLE
Status code tests for web client 

### ISSUE THREAD

**Issue by RonTuretzky** [redhat-beyond/commune#72]
![image](https://user-images.githubusercontent.com/74178515/211640014-d2c0bb74-2858-4054-90c6-1a85a7dd9470.png)

**Comment by RonTuretzky** [comment]
[lets meet /class test](https://github.com/redhat-beyond/lets-meet/blob/main/users/class_tests/sign_up_tests.py)

**Comment by EliasAndry** [comment]
we already got some site tests ..
tmr or late today ill add more
